# name: Azure Static Web Apps CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

# jobs:
#   build_and_deploy_job:
#     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#     runs-on: ubuntu-latest
#     name: Build and Deploy Job
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true
#           lfs: false
#       - name: Build And Deploy
#         id: builddeploy
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GLACIER_012F19410 }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#           action: "upload"
#           ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
#           # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#           app_location: "/" # App source code path
#           api_location: "" # Api source code path - optional
#           output_location: "build" # Built app content directory - optional
#           ###### End of Repository/Build Configurations ######

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
#     runs-on: ubuntu-latest
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         id: closepullrequest
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_GLACIER_012F19410 }}
#           action: "close"

name: cncf-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

# env:
#     VITE_STRAPI_URL: ${{ secrets.VITE_STRAPI_URL }}
#     VITE_STRAPI_TOKEN: ${{ secrets.VITE_STRAPI_TOKEN }}
#     VITE_APP_API: ${{ secrets.VITE_APP_API }}	
#   PUBLIC_SPARROW_LAUNCH_DATE: ${{ secrets.PUBLIC_SPARROW_LAUNCH_DATE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Updated to version 2 of checkout action

      - name: Set up Node.js version
        uses: actions/setup-node@v2  # Updated to version 2 of setup-node action
        with:
          node-version: '18.x'  # Use the Node.js version you need

      - name: Install Dependencies, Build, and Test
        run: |
          npm install
          npm run build
          
      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3  # Updated to version 2 of upload-artifact action
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v2  # Updated to version 2 of download-artifact action
        with:
          name: node-app
          path: build  # Ensure the correct path to extract the artifact

      # - name: Debug - List Contents of Dist
      #   run: ls -l build  # List the contents of the build directory for debugging purposes

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/build"  # App source code path
          skip_app_build: true
          skip_api_build: true
          api_location: ""  # Api source code path (optional)
          output_location: "build"
