name: cncf-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Action

      - name: Set up Node.js version
        uses: actions/setup-node@v2  
        with:
          node-version: '20'  

      - name: Install Dependencies, Build, and Test
        run: |
          npm install
          npm run build # using shell commands
      
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0  # Fetch 
        
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: npx semantic-release