name: cncf-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Updated to version 2 of checkout action

      - name: Set up Node.js version
        uses: actions/setup-node@v2  # Updated to version 2 of setup-node action
        with:
          node-version: '18.x'  # Use the Node.js version you need

      - name: Install Dependencies, Build, and Test
        run: |
          npm install
          npm run build
          
      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3  # Updated to version 2 of upload-artifact action
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v3  # Updated to version 2 of download-artifact action
        with:
          name: node-app
          path: build  # Ensure the correct path to extract the artifact

      # - name: Debug - List Contents of Dist
      #   run: ls -l build  # List the contents of the build directory for debugging purposes

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/build"  # App source code path
        #   skip_app_build: true
        #   skip_api_build: true
          output_location: "build"
