name: cncf-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Action

      - name: Set up Node.js version
        uses: actions/setup-node@v2  # Action
        with:
          node-version: '18.x'  # Here using node 18 version can change as per requirement.

      - name: Install Dependencies, Build, and Test
        run: |
          npm install
          npm run build # using shell commands

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3  # Action
        with:
          name: node-app
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v3  # Action
        with:
          name: node-app
          path: build  # define the path where our artifact is


      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/build"  # App source code path
          output_location: "build"